# Generated by Django 2.2.7 on 2021-08-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='like',
        ),
    ]
