# Generated by Django 2.2.7 on 2021-09-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_view',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
