# Generated by Django 2.2.7 on 2021-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210906_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post_view',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
