# Generated by Django 2.2.7 on 2021-06-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ImageField(blank=True, upload_to='advertisement_images/')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_phone', models.IntegerField(blank=True)),
                ('company_city', models.CharField(blank=True, max_length=50)),
                ('company_country', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
    ]
