# Generated by Django 2.2.7 on 2021-09-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210914_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_it',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_pt',
        ),
    ]
